### ISSUE TITLE
[14.0]: Tracking issue - flaky tests

### ISSUE THREAD

**Issue by deepthi** [vitessio/vitess#10620]
### Overview of the Issue

While waiting for a PR to finish running on the release-14.0 branch, @frouioui and I noticed the following tests being flaky
- [x] TestSchemaChange/online_CREATE_TABLE:  [#10674](https://github.com/vitessio/vitess/issues/10674)
- [x] TestSchemaChange/revert_revert_CREATE_TABLE:  [#10674](https://github.com/vitessio/vitess/issues/10674)
- [x] Cluster (shardedrecovery_stress_verticalsplit_heavy) - TestVerticalSplit: https://github.com/vitessio/vitess/pull/10278
- [ ] Cluster (onlineddl_ghost) mysql80:
- [x] Cluster (vreplication_across_db_versions): https://github.com/vitessio/vitess/pull/10621

### Reproduction Steps

Links to failed runs:
https://github.com/vitessio/vitess/runs/7097331285?check_suite_focus=true
https://github.com/vitessio/vitess/runs/7097333414?check_suite_focus=true
https://github.com/vitessio/vitess/runs/7097328820?check_suite_focus=true
https://github.com/vitessio/vitess/runs/7097330419?check_suite_focus=true

### Binary Version

```sh
release-14.0 commit `3319a6bf39f4547b5be01744cf53f733462ee89d`
```

### Operating System and Environment details

```sh
CI
```

**Comment by deepthi** [comment]
Re: `TestVerticalSplit` we should just start on deleting the old resharding code and this will go away.

**Comment by mattlord** [comment]
The flakiness of these two are related to MySQL 8 usage:
  Cluster (onlineddl_ghost) mysql80
  Cluster (vreplication_across_db_versions)

They are otherwise identical to other workflows which use 5.7 and are not (so) flakey. I have an open issue on this: https://github.com/vitessio/vitess/issues/10590

**Comment by GuptaManan100** [comment]
I don't think we need this issue anymore.
