### ISSUE TITLE
[VEP-4, phase 3] Switch flag definitions to be on `pflag` instead of `flag` and add make them package private.

### ISSUE THREAD

**Issue by ajm188** [vitessio/vitess#10697]
This is the general, and tracking, issue for [VEP-4](https://github.com/vitessio/enhancements/blob/main/veps/vep-4.md), [phase 3](https://github.com/vitessio/enhancements/blob/main/veps/vep-4.md#phase-3-restructuring-and-encapsulation), in which flags currently defined on the global `flag.CommandLine` in packages throughout vitess are moved simultaneously to a `pflag.FlagSet` and out of the global namespace (and therefore, out of the usage text for commands that don't consume those flags at all).

## Table of Contents

- [Packages to Move](#packages-to-move)
- [Mover's Manual](#movers-guide)

## Packages to move <a href="#user-content-packages-to-move" id="packages-to-move">#</a>

This issue is considered done when each of these is complete

(I am slowly filing issues for each of these packages, please bear with me!)

N.B. this list was generated with the following command `git grep -E "\bflag\.[A-Z]" -- go/ | cut -d':' -f1 | xargs -I{} dirname {} | uniq` and then applying some light filtering (e.g. I know that `vtadmin` is fine, and I don't care about `wrangler/testlib`). If you disagree or have questions about a package, please don't hesitate to ask!!

<details><summary>Full command with filtering I used</summary>

```
git grep -E "\bflag\.[A-Z]" -- go/ | cut -d':' -f1 | xargs -I{} dirname {} | sort | uniq | grep -Ev '(testlib|vtadmin|endtoend)' | xargs -I{} echo "- [ ] \`{}\`"
```

</details>

- [x] `go/acl` (https://github.com/vitessio/vitess/issues/10731)
- [x] `go/cmd/mysqlctl` (#11266)
- [x] `go/cmd/mysqlctld` (#11267)
- [x] `go/cmd/query_analyzer` (nothing to do now)
- [x] `go/cmd/rulesctl/cmd` (https://github.com/vitessio/vitess/issues/11276)
- [x] `go/cmd/topo2topo` (https://github.com/vitessio/vitess/issues/11277)
- [x] `go/cmd/vtaclcheck` (https://github.com/vitessio/vitess/issues/11278)
- [x] `go/cmd/vtbackup` (https://github.com/vitessio/vitess/issues/11279)
- [x] `go/cmd/vtbench` (https://github.com/vitessio/vitess/issues/11287)
- [x] `go/cmd/vtclient` (https://github.com/vitessio/vitess/issues/11288)
- [x] `go/cmd/vtcombo` (https://github.com/vitessio/vitess/issues/10993)
- [x] `go/cmd/vtctl` (https://github.com/vitessio/vitess/issues/11280)
- [x] `go/cmd/vtctlclient` (https://github.com/vitessio/vitess/issues/11281)
- [x] `go/cmd/vtctld` (https://github.com/vitessio/vitess/issues/11282)
- [x] `go/cmd/vtctldclient` (https://github.com/vitessio/vitess/issues/11283)
- [x] `go/cmd/vtctldclient/cli` (nothing to do now)
- [x] `go/cmd/vtctldclient/command` (https://github.com/vitessio/vitess/issues/11284)
- [x] `go/cmd/vtexplain` (https://github.com/vitessio/vitess/issues/11285)
- [x] `go/cmd/vtgate` (https://github.com/vitessio/vitess/issues/11286)
- [x] `go/cmd/vtgr` (https://github.com/vitessio/vitess/issues/10962)
- [x] `go/cmd/vtorc` (https://github.com/vitessio/vitess/issues/10913)
- [x] `go/cmd/vttablet` (https://github.com/vitessio/vitess/issues/11289)
- [x] `go/cmd/vttestserver` (https://github.com/vitessio/vitess/issues/11290)
- [x] `go/cmd/vttlstest` (https://github.com/vitessio/vitess/issues/11291)
- [x] `go/cmd/zk` (https://github.com/vitessio/vitess/issues/11292)
- [x] `go/cmd/zkctl` (https://github.com/vitessio/vitess/issues/11293)
- [x] `go/cmd/zkctld` (https://github.com/vitessio/vitess/issues/11294)
- [x] `go/flagutil` (https://github.com/vitessio/vitess/issues/11296)
- [x] `go/internal/flag` (https://github.com/vitessio/vitess/issues/11297)
- [x] `go/mysql` (https://github.com/vitessio/vitess/issues/10740)
- [x] `go/mysql/collations` (https://github.com/vitessio/vitess/issues/10963)
- [x] `go/mysql/collations/integration` (https://github.com/vitessio/vitess/issues/10964)
- [x] `go/mysql/collations/tools/makecolldata` (https://github.com/vitessio/vitess/issues/10965)
- [x] `go/mysql/ldapauthserver` (https://github.com/vitessio/vitess/issues/10742)
- [x] `go/mysql/vault` (https://github.com/vitessio/vitess/issues/10743)
- [x] `go/stats` (https://github.com/vitessio/vitess/issues/10741)
- [x] `go/stats/opentsdb` (https://github.com/vitessio/vitess/issues/10744)
- [x] `go/stats/statsd` (https://github.com/vitessio/vitess/issues/10745)
- [x] `go/streamlog` (https://github.com/vitessio/vitess/issues/10746)
- [x] `go/tools/asthelpergen/main` (https://github.com/vitessio/vitess/issues/11298)
- [x] `go/tools/release-notes` (https://github.com/vitessio/vitess/issues/11299)
- [x] `go/tools/sizegen` (https://github.com/vitessio/vitess/issues/11300)
- [x] `go/trace` (https://github.com/vitessio/vitess/issues/10747)
- [x] `go/vt/binlog/binlogplayer` (https://github.com/vitessio/vitess/issues/10748)
- [x] `go/vt/binlog/grpcbinlogplayer` (https://github.com/vitessio/vitess/issues/10749)
- [x] `go/vt/dbconfigs` (https://github.com/vitessio/vitess/issues/10750)
- [x] `go/vt/discovery` (https://github.com/vitessio/vitess/issues/10751)
- [x] `go/vt/grpcclient` (https://github.com/vitessio/vitess/issues/10806)
- [x] `go/vt/grpccommon` (https://github.com/vitessio/vitess/issues/10807)
- [x] `go/vt/log` (https://github.com/vitessio/vitess/issues/10808)
- [x] `go/vt/logutil` (https://github.com/vitessio/vitess/issues/10809)
- [x] `go/vt/mysqlctl` (https://github.com/vitessio/vitess/issues/10810)
- [x] `go/vt/mysqlctl/azblobbackupstorage` (https://github.com/vitessio/vitess/issues/10811)
- [x] `go/vt/mysqlctl/backupstorage` (https://github.com/vitessio/vitess/issues/10812)
- [x] `go/vt/mysqlctl/cephbackupstorage` (https://github.com/vitessio/vitess/issues/10813)
- [x] `go/vt/mysqlctl/filebackupstorage` (https://github.com/vitessio/vitess/issues/10814)
- [x] `go/vt/mysqlctl/gcsbackupstorage` (https://github.com/vitessio/vitess/issues/10815)
- [x] `go/vt/mysqlctl/mysqlctlclient` (https://github.com/vitessio/vitess/issues/10817)
- [x] `go/vt/mysqlctl/s3backupstorage` (https://github.com/vitessio/vitess/issues/10816)
- [x] `go/vt/vtorc/app` (https://github.com/vitessio/vitess/issues/11301)
- [x] `go/vt/vtorc/logic` (https://github.com/vitessio/vitess/issues/11302)
- [x] `go/vt/servenv` (https://github.com/vitessio/vitess/issues/11144)
- [x] `go/vt/sqlparser` (https://github.com/vitessio/vitess/issues/10824)
- [x] `go/vt/sqlparser/goyacc` (https://github.com/vitessio/vitess/issues/10825)
- [x] `go/vt/srvtopo` (https://github.com/vitessio/vitess/issues/10853)
- [x] `go/vt/status` (https://github.com/vitessio/vitess/issues/10854)
- [x] `go/vt/throttler/demo` (https://github.com/vitessio/vitess/issues/11303)
- [x] `go/vt/throttler/grpcthrottlerclient` (https://github.com/vitessio/vitess/issues/10855)
- [x] `go/vt/throttler/throttlerclient` (https://github.com/vitessio/vitess/issues/10856)
- [x] `go/vt/topo` (https://github.com/vitessio/vitess/issues/10857)
- [x] `go/vt/topo/consultopo` (https://github.com/vitessio/vitess/issues/10858)
- [x] `go/vt/topo/etcd2topo` (https://github.com/vitessio/vitess/issues/10859)
- [x] `go/vt/topo/k8stopo` (https://github.com/vitessio/vitess/issues/10860)
- [x] `go/vt/topo/topoproto` (https://github.com/vitessio/vitess/issues/10861)
- [x] `go/vt/topo/zk2topo` (https://github.com/vitessio/vitess/issues/10862)
- [x] `go/vt/vtcombo` (https://github.com/vitessio/vitess/issues/10888)
- [ ] `go/vt/vtctl` (https://github.com/vitessio/vitess/issues/11304)
- [x] `go/vt/vtctl/grpcclientcommon` (https://github.com/vitessio/vitess/issues/10890)
- [x] `go/vt/vtctl/grpcvtctlclient` (https://github.com/vitessio/vitess/issues/10891)
- [x] `go/vt/vtctl/vtctlclient` (https://github.com/vitessio/vitess/issues/10892)
- [x] `go/vt/vtctl/vtctldclient/codegen` (https://github.com/vitessio/vitess/issues/11305)
- [x] `go/vt/vtctld` (https://github.com/vitessio/vitess/issues/10893)
- [x] `go/vt/vterrors` (https://github.com/vitessio/vitess/issues/10894)
- [x] `go/vt/vtexplain` (https://github.com/vitessio/vitess/issues/10930)
- [x] `go/vt/vtgate` (https://github.com/vitessio/vitess/issues/10931)
- [x] `go/vt/vtgate/buffer` (https://github.com/vitessio/vitess/issues/10932)
- [x] `go/vt/vtgate/evalengine/integration` (https://github.com/vitessio/vitess/issues/10933)
- [x] `go/vt/vtgate/grpcvtgateconn` (https://github.com/vitessio/vitess/issues/10934)
- [x] `go/vt/vtgate/grpcvtgateservice` (https://github.com/vitessio/vitess/issues/10935)
- [x] `go/vt/vtgate/vschemaacl` (https://github.com/vitessio/vitess/issues/10936)
- [x] `go/vt/vtgate/vtgateconn` (https://github.com/vitessio/vitess/issues/10937)
- [x] `go/vt/vtgr` (https://github.com/vitessio/vitess/issues/10948)
- [x] `go/vt/vtgr/controller` (https://github.com/vitessio/vitess/issues/10949)
- [x] `go/vt/vtgr/db` (https://github.com/vitessio/vitess/issues/10950)
- [x] `go/vt/vttablet/customrule/filecustomrule` (https://github.com/vitessio/vitess/issues/10971)
- [x] `go/vt/vttablet/customrule/topocustomrule` (https://github.com/vitessio/vitess/issues/10972)
- [x] `go/vt/vttablet/filelogger` (https://github.com/vitessio/vitess/issues/10973)
- [x] `go/vt/vttablet/grpctabletconn` (https://github.com/vitessio/vitess/issues/10974)
- [x] `go/vt/vttablet/grpctmclient` (https://github.com/vitessio/vitess/issues/10975)
- [x] `go/vt/vttablet/onlineddl` (https://github.com/vitessio/vitess/issues/10976)
- [x] `go/vt/vttablet/sysloglogger` (https://github.com/vitessio/vitess/issues/10977)
- [x] `go/vt/vttablet/tabletconn` (https://github.com/vitessio/vitess/issues/10978)
- [x] `go/vt/vttablet/tabletconntest` (https://github.com/vitessio/vitess/issues/10979)
- [x] `go/vt/vttablet/tabletmanager` (https://github.com/vitessio/vitess/issues/10980)
- [x] `go/vt/vttablet/tabletmanager/vreplication` (https://github.com/vitessio/vitess/issues/10981)
- [x] `go/vt/vttablet/tabletserver` (https://github.com/vitessio/vitess/issues/10982)
- [x] `go/vt/vttablet/tabletserver/gc` (https://github.com/vitessio/vitess/issues/10983)
- [x] `go/vt/vttablet/tabletserver/tabletenv` (https://github.com/vitessio/vitess/issues/10984)
- [x] `go/vt/vttablet/tabletserver/throttle` (https://github.com/vitessio/vitess/issues/10985)
- [x] `go/vt/vttablet/tabletserver/vstreamer` (https://github.com/vitessio/vitess/issues/10986)
- [x] `go/vt/vttablet/tmclient` (https://github.com/vitessio/vitess/issues/10987)
- [x] `go/vt/vttest` (https://github.com/vitessio/vitess/issues/10988)
- [x] `go/vt/vttime` (https://github.com/vitessio/vitess/issues/10990)
- [x] `go/vt/withddl` (https://github.com/vitessio/vitess/issues/10989)
- [x] `go/vt/workflow` (https://github.com/vitessio/vitess/issues/10991)
- [x] `go/vt/wrangler` (https://github.com/vitessio/vitess/issues/10992)
- [x] `tool/rowlog` (https://github.com/vitessio/vitess/issues/11408)

## How to move a package's flags out of the global flagset — The Guide <a href="#user-content-movers-guide" id="movers-guide">#</a>

For each flag in the package you are tackling, you are going to want to determine if it truly should be global and available to every binary (probably flags that control logging and tracing behavior are good candidates), or if they only make sense for a particular binary or particular subset of binaries.

To see which `cmd` entrypoints actually import your package _at all_ (which doesn't actually tell you if the _value_ that flag is set to has any impact on that binary), you can run:

```
go list -f '{{ .ImportPath }}| {{ join .Deps " " }} ' ./go/cmd/... | awk -F"|" '$2 ~ " <full import path of your package here> " {print $1}'
```

The spacing in the `-f` argument to `go list` might seem arbitrary, but it's specific and important here, as it lets us do an exact match in the `awk` (e.g. you want to know if `vitess.io/vitess/go/vt/vtgate` is imported, but _not_ get false positives if someone imports `vitess.io/vitess/go/vt/vtgate/buffer`, or anything else underneath the `go/vt/vtgate/*` tree).

As an example, here are the `cmd`s that import `grpcvtgateservice`:

```
$ go list -f '{{ .ImportPath }}| {{ join .Deps " " }} ' ./go/cmd/... | awk -F"|" '$2 ~ " vitess.io/vitess/go/vt/vtgate/grpcvtgateservice " {print $1}'
vitess.io/vitess/go/cmd/vtcombo
vitess.io/vitess/go/cmd/vtgate
vitess.io/vitess/go/cmd/vtgateclienttest
```

Armed with this list, you need to make a judgement call as to whether each of these commands actually _needs_ the flags defined in your package. I don't have much to say in the way of guidance here, except to ask the domain experts of the package and the `cmd` entrypoint. This is also why we have endtoend tests, and release candidates :) 

Once you've decided, you can move your flags to a function (`RegisterFlags` is a good name, as is `InstallFlags`, which takes a `*pflag.FlagSet` as input), for example:

```diff
var myCoolFlag int

- flag.IntVar(&myCoolFlag, "my-cool-flag", 0, "this is my cool flag, but it's in the global flagset")
+ func RegisterFlags(fs *pflag.FlagSet) {
+     fs.IntVar(&myCoolFlag, "my-cool-flag", 0, "this is my cool flag, and now it's only installed on this one flagset")
+ }
```

Now that you've done that, you'll hook into `servenv`'s new hook points to ensure your flag gets installed in the right places. If you decided your flag should truly be global, you will do:

```go
func init() {
    servenv.OnParse(RegisterFlags)
}
```

If you've decided your flag belongs only on one or two commands, you'll do:

```go
func init() {
    servenv.OnParseFor("vttablet", RegisterFlags)
    servenv.OnParseFor("vtgate", RegisterFlags) // this is also why I suggest writing a function rather than inlining
}
```

**Comment by deepthi** [comment]
@ajm188 looks like are child issues are closed. Can we close this?

**Comment by ajm188** [comment]
yep!! 🔨
