### ISSUE TITLE
RFC: View Support

### ISSUE THREAD

**Issue by harshit-gangal** [vitessio/vitess#11559]
# Introduction

MySQL supports read views and updatable views. A View acts as a virtual table that is stored as a query and produces a result set when invoked. There are multiple use cases of why an application wants to use views but in this RFC we will focus on how we will add support for views in Vitess.

# Problem Statement

## Current Support
View support exists for unsharded keyspace via creating it on the underlying database.
For sharded keyspace, the support is limited to a single table as the user would be able to define sharding key for that view in the VSchema. This is useful to users who want to restrict the viewable columns for a table.

## New Support
There are limitations to the current support, like for sharded keyspace the current version is barely usable as it is very restrictive. Also, the users who are currently having views in unsharded keyspace cannot move to sharded keyspace.

This enhancement over current support will add complete support for **_readable views_** in the **_sharded keyspace_**.

# Proposal

This proposed document has its scope limited to only readable views. In the next iteration, we might extend it for updatable views, which will be a separate RFC.

## Query Serving
In the query serving path, the view definition will be cached at VTGates. The view table will be rewritten as a derived table containing the view definition. The normal query planning will follow thereafter.

An example is always helpful. For a view like:

```sql
create view user_view as select id, name from user
```

The query:

```sql
select * from user_view
```

would be rewritten to:

```sql
select * from (select id, name from user) as user_view
```

For the information_schema queries, describe queries, show queries, etc. that return the metadata, the view information would need to be injected to return the expected resultset back to the client.

## Storage / DDL Support
There are two ways we can store the view definition. Based on the location of the storage of views, there will be differences in how DDLs will be supported.

### 1: In the Topology Server (TopoServer)
The views will be stored as part of Vschema like how vindexes and tables information is stored.
Example for a keyspace:
```json
{
  "sharded": true,
  "vindexes": {...}
  "tables": {
    "user": {...},
    "user_extra": {...}
  },
  "views": {
    "user_view": "select id, name from user",
    "user_details_view": "select user.id, user_extra.col from user join user_extra on user.id = user_extra.user_id"
  }
}
```

#### DDL Support
The view definition can be added/removed using the vtctld `ApplyVSchema` command by providing the complete VSchema containing the view definition.
It can also be modified using VSchema DDL
```sql
alter vschema create view <view_name> as <select_statement>
alter vschema drop view <view_name>
```
Create View/Alter View/Drop View statements will be re-rewritten by vitess into VSchema DDLs.

Pros:
1. Atomic Update of Views definition.
2. One or more shard primary non-availability does not impact updating views definition.
3. Query will continue to serve when the TopoServer is not available.

Cons:
1. Non-availability of the Toposerver will impact updating view definition.
2. There is a size limitation on the object size that can be stored in the TopoServer. This can impact the number of views that can be created.
    * Zookeeper: 1MB hard limit
    * Etcd: 1.5MB soft limit, can request more with `--max-request-bytes`
    * K8s uses Etcd behind but has put restrictions on the sizes like 3MB and different Kubernetes cloud providers have their own limits defined.

### 2: In MySQL
The views will be stored in `_vt` the vitess internal schema where vreplication and/or online schema change metadata are stored.
View table inside `_vt` will look like:
```sql
CREATE TABLE `VIEWS` (
  `TABLE_CATALOG` varchar(512) NOT NULL DEFAULT '',
  `TABLE_SCHEMA` varchar(64) NOT NULL DEFAULT '',
  `TABLE_NAME` varchar(64) NOT NULL DEFAULT '',
  `VIEW_DEFINITION` longtext NOT NULL,
  `CHECK_OPTION` varchar(8) NOT NULL DEFAULT '',
  `IS_UPDATABLE` varchar(3) NOT NULL DEFAULT '',
  `DEFINER` varchar(93) NOT NULL DEFAULT '',
  `SECURITY_TYPE` varchar(7) NOT NULL DEFAULT '',
  `CHARACTER_SET_CLIENT` varchar(32) NOT NULL DEFAULT '',
  `COLLATION_CONNECTION` varchar(32) NOT NULL DEFAULT ''
) ENGINE=InnoDB DEFAULT CHARSET=utf8

```

#### DDL Support
Create View/Alter View/Drop View statements will be interpreted and executed as per the table definition in `_vt`.`views`.

Pros:
1. TopoServer non-availability does not impact updating views definition.
2. Query will continue to serve/buffer when one/more shards is unavailable.

Cons:
1. No ACID guarantee for updating view definition.
2. User have to manually fix the shards which have diverged view definitions.

# Decision
With the limitation on TopoServer object size, this will impose as a blocker for the users as with multiple view definition this limit might be breached and hence will make it unusable.
While storing in `_vt` has its own challenges, it does not have an achievable size limitation which makes it a viable option.

# Task
- [x] View Query Rewriting https://github.com/vitessio/vitess/pull/11195
- [x] View Storage https://github.com/vitessio/vitess/pull/11896
- [x] View DDL support https://github.com/vitessio/vitess/pull/11896
- [x] View Change Notify from VTTablet https://github.com/vitessio/vitess/pull/12115
- [x] View Definition caching in VTGates https://github.com/vitessio/vitess/pull/12124
- [x] Add Website Document https://github.com/vitessio/website/pull/1390
- [x] Add Release Notes https://github.com/vitessio/vitess/pull/12422
- [x] View Information Schema query support https://github.com/vitessio/vitess/pull/12409
- [x] View Show query support https://github.com/vitessio/vitess/pull/12409
- [x] View Describe query support https://github.com/vitessio/vitess/pull/12409
- [x] Global Routing on views
- [x] Tables and Views should be unique in a keyspace https://github.com/vitessio/vitess/pull/12409
- [ ] #12448
- [x] expand star expression in views query with column list before storing - Works with gen4 planner
- [x] restrict views support to a keyspace https://github.com/vitessio/vitess/pull/12409
- [x] Use of Schema RPC to retrieve view definition over using query at VTGate https://github.com/vitessio/vitess/pull/12375

# Call for feedback
We are looking for the community’s feedback on the above design implementation. Thank you for taking the time to read and respond.

**Comment by deepthi** [comment]
I like the feature but I'm iffy about the implementation.
Here are the concerns:
- One of the principles we want to maintain is that queries can still be served if topo is unreachable. How do we accomplish that if the view definition is stored in the topo? Perhaps you are thinking we'll consult the cache within vtgate. What is the TTL for that cache? How long can we operate in that mode?
- Topo object size is also a concern. We still support consul where objects can only be up to 512K. There will be people who hit this limit with their view definitions
- We are saying that we won't support information_schema, describe, show. This seems to be a restriction that is derived from the implementation decision of storing the view in topo. If we reverse that decision order, and decide that at least in future we want to support IS, describe and show, what will such a design look like?

**Comment by harshit-gangal** [comment]
> One of the principles we want to maintain is that queries can still be served if topo is unreachable. How do we accomplish that if the view definition is stored in the topo? Perhaps you are thinking we'll consult the cache within vtgate. What is the TTL for that cache? How long can we operate in that mode?

There is no impact this is similar to having the table sharding information. If there is no sharding information available a sharded keyspace cannot be served. If VSchema is cached once, then VTGate will continue to serve the query and does not remove it from the cache till it is not able to acquire/fetch the new value.

> Topo object size is also a concern. We still support consul where objects can only be up to 512K. There will be people who hit this limit with their view definition

To my knowledge Consul support is deprecated from all the current supported versions of Vitess. So, my opinion would be that any future decision should not rely on the limitation of the consul server.

> We are saying that we won't support information_schema, describe, show. This seems to be a restriction that is derived from the implementation decision of storing the view in topo. If we reverse that decision order, and decide that at least in future we want to support IS, describe and show, what will such a design look like?

(*On Top Of My Mind*) To support these we have to most likely run a sidecar in-memory database along with each VTGate where we can store the whole schema of the system, where we can actually create the schema/tables/views, this can help in performing any information_schema query or any schema related / metadata-related query.

The current implementation or storing the views in `_vt` will continue to have the same limitation.
We can add some additional logic in the query planner and/or query execution that can overcome these limitations temporarily.

**Comment by mattlord** [comment]
SGTM! A couple of points/questions:
1.   IMO it's worth clarifying what impact views created directly in mysqld may have on those in the vschema/vtgate, precedence, conflicts, etc. — keeping in mind sharded and unsharded keyspaces
2. Will the user also need to do `RebuildVSchemaGraph`?

**Comment by harshit-gangal** [comment]
> SGTM! A couple of points/questions:
> 
> 1. IMO it's worth clarifying what impact views created directly in mysqld may have on those in the vschema/vtgate, precedence, conflicts, etc. — keeping in mind sharded and unsharded keyspaces

* In Unsharded case: Vschema definition of views will take higher precedence over views present in MySQL. The reason is vschema declaration is optional.
* In Sharded case: Views has be declared in Vschema to be discoverable. The only way to bypass this is by using shard targeting which also means that your views are written in such a way that it does not need cross-shard query planning.

> 2. Will the user also need to do `RebuildVSchemaGraph`?

I believe this should not be the case as `ApplyVschema` and `Vschema DDL` does not require it.
I am not completely sure about this, but I can add a test and validate it.

**Comment by deepthi** [comment]
> To my knowledge Consul support is deprecated from all the current supported versions of Vitess. So, my opinion would be that any future decision should not rely on the limitation of the consul server.

This is correct and was documented in 7.0 release notes. We need to document this properly on the website so that new adopters don't use it.

One last question:
What will be the command to list the current views? and to see their definitions?
GetVSchema? If yes, let's write that down.

I don't like the fact that we are planning to claim views support without "show", that is non-intuitive. However, we anyway need to mark this as experimental. Proper documentation is going to be key, otherwise I bet the first bug report will be, I created a view and show create view doesn't work.

**Comment by harshit-gangal** [comment]
I have updated the RFC with the comments received so far.

**Comment by rsajwani** [comment]
I don't like the idea of using Topo as as full blown storage instead it should just be saving metadata (small piece of information). Topo should mainly be used as configuration information system. So my vote is for saving in MySQL. 

Also the RFC does not mention any detail around if we support cross shard views or scattered views. 

To provide consistent view or ACID guaranteed for our views is one of the many reason we should have Atomic broadcast or fault-tolerant replication instead of relying of mysql vanilla replication. But that is a separate topic to be discussed some other time.

**Comment by harshit-gangal** [comment]
> I don't like the idea of using Topo as as full blown storage instead it should just be saving metadata (small piece of information). Topo should mainly be used as configuration information system. So my vote is for saving in MySQL.
> 
> Also the RFC does not mention any detail around if we support cross shard views or scattered views.
> 
> To provide consistent view or ACID guaranteed for our views is one of the many reason we should have Atomic broadcast or fault-tolerant replication instead of relying of mysql vanilla replication. But that is a separate topic to be discussed some other time.

Thank you for reading the RFC and providing input.

RFC is about adding support for Views in Vitess for sharded and unsharded keyspace to support all the cases which includes support for cross-shard/scatter view query.

**Comment by systay** [comment]
I suggest a slight modification of how we store view definition.

The info that we'll store will be only the state that we need right now:

```sql
CREATE TABLE IF NOT EXISTS _vt.VIEWS (
  TABLE_NAME varchar(64) NOT NULL,
  VIEW_DEFINITION longtext NOT NULL,
  CREATE_STATEMENT longtext NOT NULL,
  PRIMARY KEY TABLE_NAME)
```

By storing the original create view statement in `CREATE_STATEMENT`, if we later on want to extract more information, we can look at the original request from the user.

Additionally, I think we should store the view names in the topo, together with a view version. That way, when a view is updated, the topo subscription will tell the vtgates that they need to load the new view definition from the tablet. The alternative to this would have been to lean on the healthcheck, but I think using the topo for this is simpler and faster.

I'll update the description later today if no-one has strong opinions against this suggestion

**Comment by harshit-gangal** [comment]
I like this regarding the topo storing view name and version. I think the responsibility of storing that should still lie on to the vtgate that received the view DDL statement, once the results are returned from vttablet.

**Comment by deepthi** [comment]
Storing the create_statement sounds like a good idea. Why `longtext` instead of some other type like VARBINARY or BLOB? Did you consider pros and cons before choosing the data type?

Storing the view version in the topo seems like inventing another way of keeping up with schema updates. Why is this not part of schema tracking? Are you trying to de-couple those and let views work in the absence of schema tracking?

**Comment by harshit-gangal** [comment]
In varchar we have to provide some max length which we do not know upfront. The benefit of varchar is that those columns can be indexed. I do not see in future we would index view_definition or create_statement column.

**Comment by systay** [comment]
> Storing the view version in the topo seems like inventing another way of keeping up with schema updates. Why is his not part of schema tracking? Are you trying to de-couple those and let views work in the absence of schema tracking?

Schema tracking is about tracking the schema on the mysql instances. This is different - the views will not be actually created on the shards, so there is none of that schema to track. Additionally, we are trying to move away from the current schema tracking and move the to One Schema-tracker that listens on replication traffic.

I think adding more responsibilities to the existing query serving schema tracker is a step in the wrong direction given our current plans.

**Comment by harshit-gangal** [comment]
Additional Tasks:
- [ ] Global Routing on views
- [ ] Tables and Views should be unique in a keyspace
- [ ] Views should be moved to new shards on Resharding
- [ ] Add support for `show vschema views`
- [ ] expand star expression in views query with column list before storing

**Comment by GuptaManan100** [comment]
I and @harshit-gangal discussed this approach for unsharded keyspaces recently.
Currently, Vitess supports views being created in an unsharded keyspace and vtgate treats them like any other table. 

With the changes suggested in this RFC, instead of creating a view, we will store its definition in the `_vt` table and vtgate will change the references to that table with a derived table.

The problem is that the Vitess planner isn't smart enough to always plan queries using a derived table in the best way possible. This means that we may end up with somewhat suboptimal plans for a use-case that we already supported. However, after looking at the code, we realized there is no way to support both the variants and keep the code maintainable.
