### ISSUE TITLE
Vitess Release v21 Tracking Issue

### ISSUE THREAD

**Issue by rohit-nayak-ps** [vitessio/vitess#16795]
### Feature Description
This is a tracking issue for the upcoming release of Vitess 21. Aims to hos pending todos and further document the process.
_21.0 Team: Rohit (Release Manager), Shlomi (Previous RM), Florent (Release Wizard and Next RM)_
_Clarification_: The `vitess-releaser` is automates most of the release process including creating release-related PRs. This PR is a complement to it, for tracking progress and ongoing issues/todos, but it will not be used by the tool.

### Before/Post GA

- [ ] Check benchmarks run after Florent is done with current benchmarks work
- [ ] Update Summary doc with changes to public API (GRPC / protos) in v21 wrt v20
- [x] CNCF Blog Post final Google Docs (by 18 Oct)
- [x] Summary verification (by Deepthi by 25 Oct)
- [ ] Regenerate cobra docs (Oct 29)
- [ ] Florent to validate that benchmarks are running on the v21 tag once he is done with his current development there
- [x] Florent to post in twitter
- [ ] Team: needs to update/decide on the GRPC changes to be added to the summary (https://github.com/vitessio/vitess/pull/17034) and then merge once done
- [x] Rohit:  PR to lift code freeze and merge all approved release-21.0 PRs 
- [ ] Rohit: announce EOL for v18. Document and remove references to it "everywhere"

<a name=backports-rc2></a>
## Backports for v21 RC2

- [x] https://github.com/vitessio/vitess/pull/17079 
- [x] https://github.com/vitessio/vitess/pull/17041
- [x] https://github.com/vitessio/vitess/pull/17047
- [x] https://github.com/vitessio/vitess/pull/17045
- [x] https://github.com/vitessio/vitess/pull/17019
- [x] https://github.com/vitessio/vitess/pull/17032
- [x] https://github.com/vitessio/vitess/pull/17020
- [x] https://github.com/vitessio/vitess/pull/17015
- [x] https://github.com/vitessio/vitess/pull/17017
- [x] https://github.com/vitessio/vitess/pull/17014
- [x] https://github.com/vitessio/vitess/pull/16980
- [x] https://github.com/vitessio/vitess/pull/16986
- [x] https://github.com/vitessio/vitess/pull/17006
- [x] https://github.com/vitessio/vitess/pull/17010
- [x] https://github.com/vitessio/vitess/pull/17012
- [x] https://github.com/vitessio/vitess/pull/16982

<a name=todos></a>
## Todos

- [ ] Vitess releaser: fix docker link
- [x] During RC-2 update the code examples of the vtop `release-2.14` branch to use `rc2`
- [x] Update vitess-releaser for cobradocs generation: pre-release
- [x] Update vitess-releaser checklist for vttestserver image generation: post-release
- [x] Update vitess-releaser checklist for removing Bypass Protection from `vitess` repo: post-release
- [x] Add to vitess-releaser checklist for verifying that `/releases` artifacts are created: post-release
- [x] Add to vitess-releaser checklist for GA to message CNCF about blog post (already there?)
- [x] Announce on OSS Slack, upcoming code freeze and release two weeks before code freeze: https://vitess.slack.com/archives/C0PQY0PTK/p1727123807991129
- [x] Vitess Releaser changes for v21 https://github.com/vitessio/vitess-releaser/pull/112
- [x] Announcement on OSS Slack two days before code freeze
- [x] Deepthi to check release notes Oct 2nd
- [x] CNCF Blog Post initial

<a name=backports></a>
## (Potential) Backports for v21 RC1

- [x] https://github.com/vitessio/vitess/pull/16923
- [x] https://github.com/vitessio/vitess/pull/16933
- [x] https://github.com/vitessio/vitess/pull/16936
- [x] https://github.com/vitessio/vitess/pull/16932
- [x] https://github.com/planetscale/vitess-operator/pull/613

<a name="issues"></a>
## Issues to Merge before RC code freeze 

- [x] https://github.com/vitessio/vitess/pull/16844
- [x] https://github.com/vitessio/vitess/pull/16880 
- [x] https://github.com/vitessio/vitess/pull/16833
- [x] https://github.com/vitessio/vitess/pull/16860
- [x] https://github.com/vitessio/vitess/pull/16078
- [x] https://github.com/vitessio/vitess/pull/16851
- [x] https://github.com/vitessio/vitess/pull/16897
- [x] https://github.com/vitessio/vitess/pull/16879
- [x] https://github.com/vitessio/vitess/pull/16886
- [x] https://github.com/vitessio/vitess/pull/16829
- [x] https://github.com/vitessio/vitess/pull/16378
- [x] https://github.com/vitessio/vitess/pull/16857

## Stuff to add to summary.md
- [x] atomic transactions
- [x] mysql 8.4 support

### Release artifacts
The goal of a Vitess release is to generate the following artifacts for every release including GA and intermediate RCs (and subsequent patches).

1. A git hash that marks the commit at which the release is cut.
2. Vitess binary and operator Images should be pushed to Docker Hub: should be visible at https://hub.docker.com/u/vitess like https://hub.docker.com/r/vitess/lite/tags?name=v20
3. Java packages to be pushed to Maven/SonaType
4. Notifications to Twitter/Slack
5. CNCF Blog post
6. Updated vitess.io Website documentation

### Prep Work
* Monitor PRs that need to go into the release from a few days before 
* Validate release notes 

### Dates
Tentative dates, pending schedule alignment:

- Before October 8: Pre-Requisites for a release (check environment, check GH rights, check release notes, etc)
- Tuesday 8 October: release-21.0  Code Freeze (Zoom Meeting needed)
- Between the 8th and 14h: v21.0.0 RC-1 Pre-Requisites
- Monday 14 October: v21.0.0 RC-1 Pre-Release (Zoom Meeting needed)
- Tuesday 15 October: v21.0.0 RC-1 Release (Zoom Meeting needed)
- Monday 21 October: v21.0.0 RC-2 Pre-Release (optional) (Zoom Meeting needed)
- Tuesday 22 October: v21.0.0 RC-2 Release (optional) (Zoom Meeting needed)
- Between the 22nd and 28h: v21.0.0 GA Pre-Requisites
- Monday 28 October: v21.0.0 GA Pre-Release (Zoom Meeting needed)
- Tuesday 29 October: v21.0.0 GA Release (Zoom Meeting needed)

------------------------

**Comment by rohit-nayak-ps** [comment]
Completed
