### ISSUE TITLE
Kubernetes Operator

### ISSUE THREAD

**Issue by derekperkins** [vitessio/vitess#3500]
Based on our conversation today, @enisoc is building a Vitess [Operator](https://coreos.com/operators/) for Kubernetes, to help automate setup, maintenance and routine tasks. Here is a brief list, in no particular order, of the anticipated responsibilities of the operator.

- [ ] Configure bulk load Job from an external `.sql(.gz)` file #3604 
- [x] Support user provided my.cnf files (replace and/or merge)
- [x] Add a liveness probe for the MySQL container (`mysqladmin ping`) #3584 
- [x] Use `/debug/health` endpoint in all binaries for readiness checks #3584 
- [ ] Add `/debug/nullz` endpoint in all binaries for liveness checks
- [x] Have separate Docker images for all binaries (vttablet/vtctld/vtgate/etc) #3583 
- [x] Add log rotation for `error/slow.log`
- [x] Integrate with [Orchestrator](https://github.com/github/orchestrator) (mainly registering tablets) #3605 
- [x] Optionally deploy [PMM (Percona Monitoring and Management)](https://www.percona.com/doc/percona-monitoring-and-management/index.html) #3598 
- [x] Determine why S3 / GCS credentials aren't working as expected
- [ ] Include binlogs as a part of the backup process
- [x] Register new cells with etcd
- [x] Make sure that things are ready for production - no ticking time bombs
- [ ] Kick off resharding workflows automatically
- [ ] Compute hash prior to vttablet InitContainer
- [x] Handling RollingUpdates (reparenting before killing the master)
- [ ] MySQL version upgrades - handle mysqlupgrade appropriately
- [ ] Support [gh-ost](https://github.com/github/gh-ost) for schema changes
- [ ] Support [pt-osc](https://www.percona.com/doc/percona-toolkit/LATEST/pt-online-schema-change.html) for schema changes
- [ ] Auto split shards when certain metrics are exceeded (size of shard, latency, etc)
- [ ] Use requests/limits to set defaults for `innodb_buffer_pool_instances` and `innodb_buffer_pool_chunk_size`
- [ ] Use `xfs` filesystem if available

**Comment by kfox1111** [comment]
Very interesting. Any updates on this?

**Comment by derekperkins** [comment]
@kfox1111 It's currently in progress, and hopefully will be in an (very) alpha stage sometime this week.

**Comment by kfox1111** [comment]
cool. looking forward to seeing it. Thanks. :)

**Comment by enisoc** [comment]
The WIP is posted here: https://github.com/GoogleCloudPlatform/kube-metacontroller/pull/10

**Comment by kfox1111** [comment]
Any updates to this issue?

**Comment by enisoc** [comment]
We still have a lot of work left on the checklist, but the prototype is now posted here:

https://github.com/vitessio/vitess-operator

**Comment by derekperkins** [comment]
FYI, that prototype is functional in its own right, but doesn't yet take into account the many helm changes from the past 6 months. We'll be working to port those changes into the operator so that the two are roughly at feature parity. The long-term plan is for the Operator to be the supported way to run Vitess in Kubernetes, not the helm charts currently in this repo.

**Comment by GitBytes** [comment]
@derekperkins Just curious if you have anything planned for KubeCon Seattle 2018 for this? Should I ask about this at your booth/a session? Thanks!

**Comment by derekperkins** [comment]
@GitBytes Good question. We've actually postponed doing any work on this operator in favor of fleshing out the helm charts. The helm charts just went 1.0 and are being used in production by multiple companies. They are still being improved, but are ready for use.

**Comment by derekperkins** [comment]
Feel free to swing by the booth and chat with the folks there at KubeCon, they're more than happy to answer any questions about using the helm chart to get started and handle ongoing maintenance.

**Comment by GitBytes** [comment]
@derekperkins Thank you! I will stop by and get some more information! Is this issue still something to be open then? Just curious. Cheers.

**Comment by derekperkins** [comment]
I'll go ahead and close this issue for now.

**Comment by deepthi** [comment]
@GitBytes
Look for the planetscale booth near the CNCF store

**Comment by derekperkins** [comment]
For anyone finding this issue, we just merged a major update into https://github.com/vitessio/vitess-operator and it is now being actively developed.
