### ISSUE TITLE
mysqldump: fails with default options

### ISSUE THREAD

**Issue by morgo** [vitessio/vitess#5858]
#### Overview of the Issue

mysqldump currently requires a number of options to work successfully. This convenience issue tracks what those options are, and the related issues:

- [x] (no option: SET SQL_QUOTE_SHOW_CREATE) https://github.com/vitessio/vitess/issues/5522
- [ ] `--lock-tables=off` https://github.com/vitessio/vitess/issues/5402
- [ ] `--skip-network-timeout`  https://github.com/vitessio/vitess/issues/5401 (8.0 only)
- [ ] `--set-gtid-purged=OFF`  https://github.com/vitessio/vitess/issues/5403
- [ ] `--quote-names` (issue not created yet)
- [ ] `--no-tablespaces` (issue not created yet)

A workaround to disable all of these is as follows:

```
# mysql 5.7
mysqldump  --lock-tables=off --quote-names --set-gtid-purged=OFF --no-tablespaces commerce
```
```
# mysql 8.0
mysqldump  --lock-tables=off --quote-names --set-gtid-purged=OFF --no-tablespaces --skip-network-timeout commerce
```

**Comment by harshit-gangal** [comment]
default is on for quote-names. I think it should not be an issue.

**Comment by hallaroo** [comment]
Additional tracking of issues:

- https://github.com/vitessio/vitess/issues/7408 
- https://github.com/vitessio/vitess/issues/7351

**Comment by harshit-gangal** [comment]
Two more issues reported:

https://github.com/vitessio/vitess/issues/7483
https://github.com/vitessio/vitess/issues/7482

**Comment by deepthi** [comment]
As we discussed offline, it is reasonable to not support `mysqldump` with default options as long as we clearly document how to use it.
Documentation that needs to be reviewed/updated:
https://vitess.io/docs/user-guides/configuration-basic/exporting-data/#mysqldump
https://vitess.io/docs/user-guides/migration/migrate-data/

We say we recommend `godumper` but we should document how to use `mysqldump` as well.

**Comment by harshit-gangal** [comment]
I think we should document how to move data to Vitess using VReplication and recommend that over go-mydumper or mysqldump

**Comment by deepthi** [comment]
We already have the docs. Maybe we should move the VReplication method to the top and push "stop-the-world" to second place.
