### ISSUE TITLE
Messaging Wishlist

### ISSUE THREAD

**Issue by derekperkins** [vitessio/vitess#5882]
I'm hoping to do some significant messaging work in Q2 and this is a list of various features that exist in other queueing systems that would be great if they were supported in Vitess.
- [ ] Use vreplication for topics - the current implementation of topics is brittle and only supports same-tablet subscribers
- [ ] Allow filtered topic subscriptions #5180 - this builds on the prior task and should work once vreplication supports filters
- [ ] Always include a json meta column - this allows for future meta improvements without breaking compatibility #5415
- [ ] Merge those meta keys with arbitrary user key value pairs - see SQS https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-message-attributes.html
- [ ] Support min/max backoff - rather than doubling forever, provide bounds
- [ ] Support priority queues: add an optional priority column (tinyint)
https://github.com/bgadrian/data-structures/tree/master/priorityqueue
https://www.rabbitmq.com/priority.html
- [ ] Allow for storing message errors/status that aren't delivered to consumers - see Google Cloud Tasks https://godoc.org/google.golang.org/genproto/googleapis/cloud/tasks/v2#Task
- [ ] Support message lease extension - related to #5796, this lets smart clients extend the deadline for messages they have received and intend to process https://cloud.google.com/pubsub/docs/reference/rest/v1/projects.subscriptions/modifyAckDeadline
- [ ] Explicit nacks - today the only way for a message to be redelivered is to wait for the message timeout. By allowing for nacks on failure, you can avoid unnecessary delays.
- [ ] Support message state field - Possibly related to the prior item, this would enable new states like "failed". Today, this can be modeled by setting `time_next` to a very large number.
