### ISSUE TITLE
Make emergency reparents more robust.

### ISSUE THREAD

**Issue by enisoc** [vitessio/vitess#6206]
We previously did a lot of work to make TabletExternallyReparented and PlannedReparentShard more robust (#5151, #5172, #5391). We plan to do the same for EmergencyReparentShard (ERS) next.

The main goal is to automate "lossless" unplanned failovers. When running with semi-sync enforced (async fallback disallowed), it's possible under the right circumstances to avoid losing committed transactions even when the current master goes down unexpectedly. Currently, the user must perform manual checks before calling ERS in order to ensure such a lossless failover. We plan to teach ERS to perform those checks itself and optionally require them to pass before executing a failover.

## Assumptions

Our goal is to guarantee that executing the new EmergencyReparentShard (ERS) with default options will neither lose committed transactions nor cause split brain under the following set of assumptions.

ERS will still be usable if these conditions are not all met, but in that case it may be possible to cause split brain and/or data loss by executing ERS.
Also note that meeting all these conditions does not imply that data loss is impossible; the goal is to guarantee that executing ERS will not make anything worse.
For example, if all tablets for a shard go down simultaneously and their disks are wiped, you will lose all changes since the last backup.

1. We define a committed transaction as any transaction that has made it into the binary log on the master and additionally has made it into the relay log of at least one other tablet of any type (replica, rdonly, etc) in any cell.
   Note that this definition is independent of all of the following: whether that tablet sends an ACK; whether the master receives an ACK; and whether success is ever reported to the client.
1. We assume Vitess is the only entity directly issuing MySQL replication management commands.
   Anything else (human or automated) participating in replication management does so only via public Vitess APIs (e.g. vtctl).
1. We assume that the only clients replicating from the master MySQL are other Vitess tablets.
1. We assume single-master, single-layer replication.
1. We assume MySQL is configured with semi-sync enabled, requiring at least one ACK, and with fallback to async forbidden.
   In particular, we assume Vitess is configured with the `-enable_semi_sync` flag, so that vttablet toggles MySQL semi-sync accordingly prior to any change in replication state.
1. We assume by default (unless overridden with flags) that it's preferable to maintain consistency at the expense of availability if necessary.
   For example, if this new ERS does not see a way to guarantee a lossless failover, it will refuse to take any action unless told to override safety checks.

## New Design

The new EmergencyReparentShard will consist of the following steps:

1. For each tablet in the shard:
   - Stop IO thread (but keep SQL thread running) and get replica status.
   - If slave status is ErrNotSlave, use DemoteMaster to stop it and get its position.
   - If at any point you have received responses from N-1 tablets, abort the last one and continue.
   - If at any point more than 1 tablet call has failed, abort ERS.
   - If at any point the timeout for this phase expires, abort ERS,
     _unless_ all the remaining tablets' aliases are included in the `--ignore_unreachable_tablets` set.
2. Determine Valid Candidates, and Wait
   - If we have N-1 responses complete with full slave status, and full GTIDSets for
     executed position, use `mysql.FindErrantGTIDs()` to detect errant GTIDs.
   - Use `mysql.AllPositionsComparable()` to check that we can create a total ordering.
     - If we can't create a total ordering, abort ERS.
   - If any replica has errant gtids - throw them out from the group of valid candidates.
   - If we were told to elect a specific new master, remove all other candidates from the set.
   - If there are remaining replicas, wait for them to apply their relay logs, otherwise abort.
3. Promote the winning candidate to master.
4. Reparent all other tablets to the winning candidate.
   - Wait for at least one successful reparent, rest are best effort.

## Implementation Plan

- [x] mysql: Add `Union()` to `GTIDSet` interface and implement for all flavors (#6180).
- [x] mysql: Add errant GTID detection functions.
  - [x] Add `Comparable()` method to `Position` struct, which returns whether this position
    is comparable against another position.
  - [x] Add `AllPositionsComparable()` function that accepts a list of Positions and returns
    true if and only if every Position is `Comparable()` with every other Position.
  - [x] Add `FindErrantGTIDs()` function that accepts a list of SlaveStatuses and returns
    a list of GTIDSets containing GTIDs known to be errant for each respective SlaveStatus.
- [x] tabletmanager: Add option to `StopReplicationAndGetStatus()` to stop only IO thread.
- [x] tabletmanager: Return file:pos-based replication positions in addition to GTID-based positions.
  - [x] `StopReplicationAndGetStatus()` (add file:pos-based positions for both executed and relay log)
  - [x] `DemoteMaster()` (change `string` return value to a struct)
- [x] tabletmanager: Make `WaitForPosition()` accept either file:pos or GTID-based positions.
- [ ] wrangler: Rewrite EmergencyReparentShard with new design.
  - [ ] Add `--ignore_unreachable_tablets` flag.
  - [ ] Implement the new design logic.
  - [ ] Add ACTION REQUIRED release note that upgrades must follow the recommended order,
    since we are relying upon new tabletmanager RPC functionality.

**Comment by shlomi-noach** [comment]
Some questions/notes:

> If at any point you have received responses from N-1 tablets, abort the last one and continue.

Can you please clarify why stop at N-1? (e.g. what if the Nth server is the most advanced of them all?)

> If at any point more than 1 tablet call has failed, abort ERS.

IMHO and based on successful `orchestrator` behavior, it's OK if some of the replicas fail. In fact, there may well be a correlation between master and replica failure (both happen to be in same cell/region?) so it's not unexpected that a replica will also be unresponsive when the master dies.
`orchestrator` is permissive and doesn't really care _how many_ replicas are unresponsive as long as _some_ replicas (>=1) are responsive and all confirm it's assessment that the master is dead.
But, if you'd like to play safe, how about if you ignore up to `minority` of failed replicas?

> unless all the remaining tablets' aliases are included in the --ignore_unreachable_tablets set.

In `orchestrator` I'm also able to "downtime" a server, for whatever reasons I may have. Downtimed servers are also ignored in evaluations such as this. Just a thought.

> Compute the high-water mark among all positions seen ...

Notes from our video conversation, there's two types of errant transactions: salvageable and lost.
An errant transaction is "salvageable" if it can still be found in the server's binary logs, and it is "lost" if the binary log containing the transaction has been purged.

A server that has "lost" errant transaction is a big no-no (unless it's the only one left to go with); A server with salvageable errant transactions can still donate those transactions to what new replicas are assigned to it.

At any case, we prefer that the users are alerted whenever an errant transaction scenario appears. Errant transactions should not happen, and if they do happen, need to be investigated and resolved during peaceful time. At the time of a crash scenario, we normally don't expect an errant transaction case.

We also need to decide (or allow configuration) what to do if the replicas are lagging too much; do we wait for them to consume the relay logs (and lose availability)? Do we _just promote_ (and lose transactions)? Do we have any timeout?

> 4. Wait until any one of the candidates executes everything up to the high-water mark

Again, notes from our conversation: in a low-lag scenario (which is something to strive for), by the time operator/orchestrator detect master failure, the replicas will have consumed what remaining relay logs they have. That's the normal case.

---

Extra thoughts:

The above process does not take into account these scenarios:

0. There's diversity of MySQL versions. Say we were in the middle of an upgrade. One replica is `5.7`, one is `8.0`. MySQL does not support replication `8.0`->`5.7` so we prefer to promote `5.7`. But what if `8.0` has higher watermark?
0. Is it possible one of the replicas is undertaking some operation which should not be intrrupted? Like a backup?

Also (notes from our discussion)

- We should be able to identify some errant GTID transactions that are safe to ignore: a `FLUSH SLOW LOGS` command, for example, or a `ANALYZE TABLE`. These do not change data and for some of those commands I actually think it's a MySQL bug that they at all produce a GTID entry.
Anyhow, we might be able to automate away safe cleanup of such errant transactions.

**Comment by PrismaPhonic** [comment]
```
Can you please clarify why stop at N-1? (e.g. what if the Nth server is the most advanced of them all?)
```

The idea was that we wanted to design this in a way where we don't have to know who the old master was. If we actually get slave status back from N-1, then we've spoken to all replicas without explicitely needing to know who the master was.

**Comment by shlomi-noach** [comment]
> If we actually get slave status back from N-1, then we've spoken to all replicas without explicitely needing to know who the master was.

Thanks for clarifying! It's not clear in the text that those are _specific_ N+1 replicas (the "real" replicas, excluding the master).

**Comment by enisoc** [comment]
> Can you please clarify why stop at N-1? (e.g. what if the Nth server is the most advanced of them all?)

We define a successful transaction as any transaction that made it to at least 2 of these N tablets. That means if we get answers from N-1 tablets, we know we've observed all successful transactions. That last tablet we ignore could be the master, but it doesn't have to be if the master is actually responding.

> It's not clear in the text that those are specific N+1 replicas (the "real" replicas, excluding the master).

The text actually refers to _any_ `N-1` tablets. We do not specifically exclude anything. Note that `N` is the total number of tablets in the shard, of _any_ type (master, replica, rdonly, backup, restore, etc.).

> it's OK if some of the replicas fail

Our goal for this phase of implementation is, by default, to only proceed if we can guarantee no transaction will be lost. In case the user wants to move forward despite the risk of losing data, we will offer options to override these default safety checks. In the future, we can also add heuristics like checking for majority, but we want to get the core, completely lossless case done first.

> Downtimed servers are also ignored in evaluations such as this.

That's an interesting alternative to the flag we were planning, which is admittedly awkward. Maybe we should instead ask the user to mark something in the tablet record to indicate it should be ignored, as you suggested. Alternatively we could tell users to delete the tablet record if they really want it to be ignored.

> At any case, we prefer that the users are alerted whenever an errant transaction scenario appears.

In our current design, we drew the line slightly differently: if we can automatically take action to improve the situation in a way that is guaranteed to be safe, then we will take action. That's why we check to see if there is a good candidate for promotion among those tablets that have no errant gtids detected. If such a candidate exists, we believe it should be safe to promote it. WDYT?

> We also need to decide (or allow configuration) what to do if the replicas are lagging too much; do we wait for them to consume the relay logs (and lose availability)?

In keeping with our overall goal for this phase of taking action, by default, only when we can guarantee no transaction will be lost, we decided to abort and do nothing if no tablet catches up on its relay logs within the timeout configured as an argument to the emergency reparent command.

> There's diversity of MySQL versions.

You right that we don't handle this yet. For now, we are prioritizing consistency over availability, so we understand there may be cases where things get stuck. If there is a possibility of version skew causing data loss, we would need to reevaluate the plan.

> Is it possible one of the replicas is undertaking some operation which should not be intrrupted?

For Vitess-controlled operations, each tablet uses a mutex to ensure it only executes one tabletmanager RPC at a time. So if an operation is still ongoing, that tablet will not respond to our "stop replicating and get status" RPC until the other operation terminates. One exception is xtrabackup, which we allow to run in the background. I don't know whether it's safe to reconfigure replication while xtrabackup is running.

**Comment by shlomi-noach** [comment]
> That's why we check to see if there is a good candidate for promotion among those tablets that have no errant gtids detected. If such a candidate exists, we believe it should be safe to promote it. WDYT?

Yes, that's a safe & good approach!

> For Vitess-controlled operations, each tablet uses a mutex to ensure it only executes one tabletmanager RPC at a time. So if an operation is still ongoing, that tablet will not respond to our "stop replicating and get status" RPC until the other operation terminates.

Oh, interesting. Thanks!

**Comment by sougou** [comment]
Overall plan looks good. Couple of nits:

> * If at any point you have received responses from N-1 tablets, abort the last one and continue.

I believe this should exclude the current master. Otherwise, that one replica could have received a stray transaction.

> If we have N-1 responses complete with full slave status, and full GTIDSets for
> relay log position, use `mysql.FindErrantGTIDs()` to detect errant GTIDs.
> * Remove detected errant GTIDs from each tablet's set, then continue.

I'd say we should fail here by default, and may be add an option to exclude errant gtids.

**Comment by deepthi** [comment]
Given the complexity of this design, could one of you list out the testcases / corner cases that should be addressed by the implementation?

**Comment by PrismaPhonic** [comment]
> Overall plan looks good. Couple of nits:
> 
> > * If at any point you have received responses from N-1 tablets, abort the last one and continue.
> 
> I believe this should exclude the current master. Otherwise, that one replica could have received a stray transaction.
> 

I thought the purpose of this design was so that we could be ignorant of who the current master is?

> > If we have N-1 responses complete with full slave status, and full GTIDSets for
> > relay log position, use `mysql.FindErrantGTIDs()` to detect errant GTIDs.
> > 
> > * Remove detected errant GTIDs from each tablet's set, then continue.
> 
> I'd say we should fail here by default, and may be add an option to exclude errant gtids.

The issue here, is what if a replica has errant GTIDs, but wouldn't hit the high water mark regardless? I think we should abort if the only replica/s that hit the high water mark have errant GTIDs, but it's useful to determine what the high water mark is first, removing errant GTIDs from that consideration, so we can determine if we even have a valid candidate that is errant GTID free.

**Comment by deepthi** [comment]
@PrismaPhonic is this still required? AFAICT all RPCs used by ERS are already present in 7.0 and no new RPCs are being introduced in the PR that addressed this issue.
```
Add ACTION REQUIRED release note that upgrades must follow the recommended order,
since we are relying upon new tabletmanager RPC functionality.
```

**Comment by PrismaPhonic** [comment]
> introduced in the PR that fixes this issue.

Correct. There are no new RPCs, so I imagine we already missed the boat if this isn't already in 7.0 release notes. @enisoc?

**Comment by deepthi** [comment]
> > introduced in the PR that fixes this issue.
> 
> Correct. There are no new RPCs, so I imagine we already missed the boat if this isn't already in 7.0 release notes. @enisoc?

This isn't going into 7.0, so there's nothing to do.

**Comment by enisoc** [comment]
If all the new RPCs made it into 7.0 before we started using them in 8.0, then I guess we accidentally did this in the slower, safer way. We don't need a release note in that case.

**Comment by aeschylus** [comment]
I'm still experiencing a problem with emergency reparenting (I believe).

I'm using planetscale for a project and recently received this message:

```
.-.primary: primary is not serving, there is a reparent operation in progress
```

What is going on?

**Comment by shlomi-noach** [comment]
@aeschylus just making sure, if this is a `planetscale` production issue, did you open a ticket with `planetscale`?

**Comment by fooforge** [comment]
> I'm still experiencing a problem with emergency reparenting (I believe).
> 
> I'm using planetscale for a project and recently received this message:
> 
> ```
> .-.primary: primary is not serving, there is a reparent operation in progress
> ```
> 
> I'm unable to connect to the database in any way. This is on a production web app. None of my customers can use my app.

@aeschylus You can reach us at https://support.planetscale.com/. Please provide us with the name of your database and the affected branch, and let us know when this has last occurred so that we know where to start looking. Thanks!
