### ISSUE TITLE
Schema tracking v1

### ISSUE THREAD

**Issue by systay** [vitessio/vitess#7994]
See #7995 for background

# Suggested solution

## 1. vttablet schema version tracking
Primary tablets will keep track of the schema of all tables of the underlying MySQL database. 
This includes column names, types and nullability.
Keeping track will be done by copying the relevant information_schema data to a new table in the `_vt` database on the primary.
Whenever a change is noticed, we can push out an event to the vtgates, informing them that they need to reload schema.

_ Questions: _ 
How do we notice that the underlying schema has changed?

## 2. vtgate queries a primary tablet
In this schema tracking V1, vtgate will simply talk with the first shard primary and keep the schema from the tablet mirrored in its local state.

The schema data fetched this way will be applied as authoritative columns for tables that the user has not already done so for. This was, users will be able to override the actual mysql schema, when that is needed.

- [x] At tablet startup - check if the necessary `_vt.schema` tables exist, if it is missing, it needs to be created.
- [x] When doing schema check, we can join the `_vt.schema` table with the `information_schema.columns` to figure out what has changed, and if something has changed, publish in the health check and update the `_vt.schema`
- [x] On the vtgate side, receive these events and trigger a schema update
- [x] Update the vtgate vschema copy with authoritative columns.

**Comment by systay** [comment]
Edited this and #7995 to align them and reflect our current understanding
