### ISSUE TITLE
Task: delete deprecated discoverygateway and legacy healthcheck code

### ISSUE THREAD

**Issue by deepthi** [vitessio/vitess#9218]
As part of #5750, we implemented a new gateway called `tabletgateway` and deprecated the old one called `discoverygateway`.
We have had several releases since then, and `tabletgateway` is now stable enough. We can now start deleting some of the old code.

Blocker: vtctld ui still uses legacy healthcheck. We need to either move that to the new healthcheck, or deprecate/delete that first.

Tasks
- [x] In release 13.0, deprecate and ignore `-gateway_implementation` flag #9482 
- [x] delete discoverygateway.go #9500 
- [x] Optionally also delete `Gateway` interface #9852
- [x] fix vtctld realtime_status to not use legacy healthcheck #9358
- [x] delete legacy_healthcheck.go and any related structs that are no longer needed https://github.com/vitessio/vitess/issues/10454
- [x] In release 14.0 delete `-gateway_implementation` flag #9852

EDIT Mar 8, 2022:
Split deletion into two separate tasks because of the dependency on #9358

**Comment by deepthi** [comment]
All tasks are now complete. Thank you for all your work on this @frouioui!
