### ISSUE TITLE
RFC: Handle reserved/tainted connections better

### ISSUE THREAD

**Issue by harshit-gangal** [vitessio/vitess#9706]
## Problem Statement

Vitess has a feature where it allows changing session-level system settings on a connection. In Vitess terminology, these connections are called tainted connections. As the connection properties are modified on those connections, they cannot be returned to the originating connection pool. After the client session is closed, these connections are closed.

As these connections cannot be returned to the pool, till the lifetime of the session they are reserved for those sessions. On the VTGate side, these connection ids are stored on the session. They are called reserved connections. Any further query will use these reserved connections to send the query to MySQL.

The usage of this feature was meant to be restricted for one-off cases. It was advised that the Vitess users should configure the MySQL properties in such a way that they do not need to use this feature (i.e. change the system properties upfront at MySQL level, to match the properties the application requires).

Over time we have seen that Vitess connection will not come from a single application but multiple different applications with different application frameworks. Due to this, every application framework will try to set different kinds/values various system properties. This causes many or all of the connections between vttablet and MySQL to be reserved connections for the session, and we will run into the maximum allowed number of MySQL connections.

Also, we have seen that sometimes Vitess users do not have control over changing the system settings at the MySQL level, and hence it causes MySQL to run out of connections because of the above reserved connections problem.

To avoid these scenarios, we have to come up with a design that can handle these cases and deal with application frameworks setting the system variables upfront on the connections.

#### Proposal 1:
Set the appropriate session properties after acquiring a connection from the pool and reset the settings on returning to the pool.

#### Proposal 2:
For MySQL 8.0+ we can use optimizer hint SET_VAR as a query comment. The optimizer hints are only applicable to the scope of a single query. This will not change the connection permanently and hence can be returned to the pool.

#### Proposal 3:
In the transaction pool, currently, we have an originating pool and a transactions registry where active transactions live (currently tainted connections are also present there without having an active transaction). 
The proposal is to write a new pool implementation which can handle the connection which have settings applied on it.
Any request comes that also updates/changes the system settings, gets the connection from this new pool which will know how to efficiently provide and manage such connections

## Benchmarks

| Proposal | Description | Operations | Time per Op |
| ------------ | --------------- | --------------- | ---------------- |
| 2 | System variables as query hints | 2233 | 549261 ns/op |
| 1 | System variables exec before each query exec | 1663 | 651643 ns/op |
| 1 | System variables exec along with query exec | 1946 | 553904 ns/op |
| Existing | One-time system variables exec and reusing same connection |2444 | 482357 ns/op |

## Implementation

From the above benchmark, there is the overhead of setting system variables before running a query. 
But, setting system variables as query hints do not have much overhead and gives us headway before implementing the caching layer for tainted connections.

We have implemented Proposal 2, but this only supports a subset of system variables as the optimizer hints have a limitation on it.

The next step is to implement Proposal 3 and perform a benchmark with the existing feature. A reasonable degradation should be acceptable as it avoid the MySQL from running out of connections

## Tasks
- [x] Proposal 2 PR: https://github.com/vitessio/vitess/pull/9641
- [x] Proposal 3

**Comment by frouioui** [comment]
The Pull Request for the micro-benchmarks is available here: https://github.com/vitessio/vitess/pull/9681

**Comment by harshit-gangal** [comment]
Proposal 3 Task List (live):
- [ ] Add new pool implementation
- [ ] Benchmark the implementation with existing one
- [ ] Integrate the new pool into the transaction engine.
- [ ] Add vttablet level e2e tests
- [ ] Change vttablet API to receive system settings as ExecuteOptions
- [ ] Shift VTGate calls to use newer API
Improvements:
- [ ] Avoid passing of settings on each call to vttablet from vtgate

**Comment by harshit-gangal** [comment]
Vttablet Query Exec Changes
- If transaction exists then we can assume that the connection that is tied to that transaction already have those settings applied.
- We need to acquire the connection with the settings applied in 2 cases
	1. Start of transaction
	2. Query execution outside of transaction

VTGate Query Exec Changes
- Currently no changes are needed, later we have to move away from calling Reserve Apis of vttablet.
